<?php
use PFBC\Form;
use PFBC\Element;
 
//$form = new Form("cadastro-pessoa");
$form = new Form("vertical");
$form->configure(array(
	'action'=>SITE."cadastro/cadpessoa",
    "prevent" => array("bootstrap", "jQuery", "focus")
));
$form->addElement(new Element\Textbox("Nome completo:", "full_name",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("RG:", "rg",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("cpf:", "cpf",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Rua:", "rua",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Numero:", "numero",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Setor:", "setor",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Cep:", "cep",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Estado:", "estado",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Cidade:", "cidade",array(
		'class'=>'form-control',
		'required'=>1,
)));

$form->addElement(new Element\Phone("E-mail:", "email",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Phone("Telofone:", "telefone",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Phone("Celular:", "celular",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Usuario:", "user",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Login:", "login",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Senha:", "senha",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Confirmar senha:", "Confirma Senha",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Ramo de atividade:", "ramo-de-atividade",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Textbox("Cargo de interesse:", "cargo",array(
		'class'=>'form-control',
		'required'=>1,
)));
$form->addElement(new Element\Button('Cadastrar','submit'));
$form->addElement(new Element\Button("Cancel", "button", array(
    "onclick" => "history.go(-1);"
)));
?>
<div class='col-md-8 col-md-offset-2'>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Cadastre sua empresa</h3>
  </div>
  <div class="panel-body">
  		<?php
		$form->render();
		?>
  </div>
</div>
</div>