		</div>
	</div>
    </div>
	<div class="container-fluid">
		<div class="row text-white footer">
			<div class="col-md-3 col-md-offset-1">
				<h2>Sobre Nós</h2>
				<h4>Indefinido</h4>
			</div>
			<div class="col-md-4">
				<h2>Redes Sociais</h2>
				<h4>Indefinido</h4>
			</div>
			<div class="col-md-4">
				<h2>Alguma coisa</h2>
				<h4>So nao imaginamos inda</h4>
			</div>
			<div class="col-md-4 col-md-offset-4 text-center text-white">
				JobEasy v<?=VERSION;?> <?=date("Y");?> &copy; - Todos os direitos reservados
			</div>
		</div>
	</div>
</body>
</html>