<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Bruno C. Santos">
	<meta name="generator" content="HXPHP Framework v1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?=$view_title;?></title>
	<link rel="shortcut icon" href="<?=IMG;?>favicon.ico" type="image/x-icon">
	<?=$add_css;?>
	<link rel="stylesheet" href="<?=CSS;?>bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>css-geral.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>style.css" type="text/css">
	<script type="text/javascript" src="<?=JS?>jquery.min.js"></script>
	<script type="text/javascript" src="<?=JS;?>bootstrap.min.js"></script>
	<?=$add_js;?>
	<script type="text/javascript" src="<?=JS;?>main.js"></script>
</head>
<body >
	<div class="full bg" id="header">
		<div class="container">
			<div class="col-md-9">
				<a href="<?=SITE;?>" class="logo col-md-offset-4 col-md-4">
					<div class="col-md-12">
						<img class="img" src="<?=IMG;?>hxphp-logo.png" alt="JobEasy">
					</div>
				</a>
			</div>
			<div class="col-md-3 text-white">
				<button id="btn-login" class="btn btn-success col-md-9 col-md-offset-1">Login</button>
				<button id="btn-fechar-login" class="btn btn-danger" style="display: none">X</button>
				<div class="col-md-12" id="login" style="display: none">
					<form method="post" class="form-horizontal" action="<?=SITE;?>login/logar/" role="form">
						<div class="form-group">
						    <label for="username">Email</label>
						    <input type="text" required="required" class="form-control" id="username" name="username" placeholder="Usuário">
						</div>
						<div class="form-group">
						    <label for="password">Senha</label>
							<input  type="password" required="required" class="form-control" id="password" name="password" placeholder="Senha">
						</div>
  						<button type="submit" class="btn btn-primary">Logar</button>
					</form>
				</div>
			</div>
		</div>
	</div>

	<?=$view_message;?>

	<div class="container">
			<div class="col-md-12">

	<script type="text/javascript">
	$("#btn-login").click(function() {
		$("#login").show('fast');
		$("#btn-fechar-login").show();
	});
	$("#btn-fechar-login").click(function() {
		$("#login").hide('fast');
		$("#btn-fechar-login").hide();
	});
	</script>