   <section id="index-container">
        <div class="row">
            <div class="col-md-5">
                <div class="col-md-12">
                    <p>Quer ser bem sucedido?<br>Encontrar o emprego dos sonhos?<br>Faça já sua pré inscrição para o maior sistema de empregos do Basil!</p>
                </div>
                <div class="col-md-12">
                    <a href="<?=SITE?>Cadastro/pessoa" id='cadastro-pessoa' class='col-md-12'>Cadastro Pessoa</a>
                </div>
            </div>
            <div class="col-md-offset-1 col-md-5">
                <div class="col-md-12">
                    <p>Precisa de funcionários?<br>Dificuldades para encontrar empregados que atendem usas necessidades?<br>Nós procuramos para você!<br>Cadastre já a sua empresa!</p>
                </div>
                <div class="col-md-12">
                    <a href="<?=SITE?>Cadastro/empresa" id='cadastro-empresa' class='col-md-12'>Cadastro Empresa</a>
                </div>
            </div>
        </div>

    </section>
